""""
Django settings for HadiHesabAI project.
Generated by 'django-admin startproject' using Django 5.1.6.
"""

import os
from pathlib import Path
from celery.schedules import crontab

# ------------------------------------------
# مسیر اصلی پروژه
# ------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# کلیدها
SECRET_KEY = "123"


# ------------------------------------------
# Debug / Hosts
# ------------------------------------------
DEBUG = True

ALLOWED_HOSTS = [
    "*",                # اجازه همه — مناسب برای توسعه
]

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1',
    'http://localhost',
    'http://185.252.86.179',
    'http://192.168.1.0',
    'http://192.168.1.1',
    'http://192.168.1.100',
]

# ------------------------------------------
# Installed Apps
# ------------------------------------------
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # اپ‌های پروژه
    'ai.apps.AiConfig',

    # کتابخانه‌ها
    'rest_framework',
    'django_celery_beat',
    'import_export',
    'channels',
]

# ------------------------------------------
# Middleware
# ------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ------------------------------------------
# URL
# ------------------------------------------
ROOT_URLCONF = 'HadiHesabAI.urls'

# ------------------------------------------
# Templates
# ------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ------------------------------------------
# WSGI / ASGI
# ------------------------------------------
WSGI_APPLICATION = 'HadiHesabAI.wsgi.application'
ASGI_APPLICATION = 'HadiHesabAI.asgi.application'

# ------------------------------------------
# Database  (بدون تغییر)
# ------------------------------------------

# ------------------------------------------
# Channels & WebSocket
# ------------------------------------------

# توصیه برای Production: Redis
# ولی برای الان InMemory مشکلی ندارد
CHANNEL_LAYERS = {
    'default': {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# ------------------------------------------
# Password Validators
# ------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ------------------------------------------
# Language & Time
# ------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ------------------------------------------
# Static & Media
# ------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ------------------------------------------
# Celery Config
# ------------------------------------------
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_BEAT_SCHEDULE = {
    'get-customers-data-nightly': {
        'task': 'ai.tasks.get_customers_data',
        'schedule': crontab(hour=3, minute=0),
    },
    'predict_customer_data': {
        'task': 'ai.tasks.predict_customer_data',
        'schedule': crontab(hour=5, minute=0),
    },
    'create_training_files': {
        'task': 'ai.tasks.train_model_files',
        'schedule': crontab(hour=4, minute=0),
    },
}

# ------------------------------------------
# Security Settings
# ------------------------------------------
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
