version: '3.8'

services:
  django:
      build: .
      ports:
        - "8000:8000"
      volumes:
        - .:/app
      command: [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
      restart: always
      depends_on:
        - redis
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A HadiHesabAI worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A HadiHesabAI beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis