# Generated by Django 5.1.6 on 2025-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_training'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainingn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Category', models.CharField(blank=True, max_length=100)),
                ('Grouh', models.TextField(blank=True)),
                ('Sarfasl', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
